platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:kunhum/XKToolSetRepo.git'
use_modular_headers!

target 'XKCurrency_Example' do
  pod 'XKCurrency', :path => '../'

  target 'XKCurrency_Tests' do
    inherit! :search_paths

    
  end
end
